const swaggerAutogen = require('swagger-autogen')();

const outputFile = './swagger_output.json';
const endpointsFiles = ['./app.js'];

const doc = {
  info: {
    version: '1.0.0',
    title: 'Places API',
    description: 'Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      name: 'Places',
      description: 'Endpoints',
    },
  ],
};

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  // eslint-disable-next-line global-require
  require('./app'); // Your project's root file
});
