const swaggerAutogen = require('swagger-autogen');

const outputFile = './swagger/swagger_output.json';
const endpointsFiles = ['./app.js'];

const doc = {
  info: {
    version: '1.0.0',
    title: 'Places API',
    description: 'Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      name: 'Places',
      description: 'Endpoints',
    },
  ],
  definitions: {
    Places: {
      $name: 'Restaurante',
      $x: 27,
      $y: 12,
      opened: '12:00',
      closed: '18:00',
    },
    AvailablePlaces: {
      name: 'Praça',
      status: 'Aberto',
    },
  },
};

swaggerAutogen()(outputFile, endpointsFiles, doc);
